/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetExpenses200,
  GetExpensesParams,
  GetExpensesSummary200,
  GetExpensesSummaryParams,
  GetMe200,
  PostExpenses201,
  PostExpensesBody,
  PostRefreshToken200,
  PostRefreshTokenBody,
  PostRegisters201,
  PostRegistersBody,
  PostSessions200,
  PostSessionsBody
} from './schemas';

import { customInstance } from '../lib/orval-mutator';
export const getGoTrackApi = () => {
const postRegisters = (
    postRegistersBody: PostRegistersBody,
 ) => {
      return customInstance<PostRegisters201>(
      {url: `/registers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRegistersBody
    },
      );
    }
  
const postSessions = (
    postSessionsBody: PostSessionsBody,
 ) => {
      return customInstance<PostSessions200>(
      {url: `/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postSessionsBody
    },
      );
    }
  
const getMe = (
    
 ) => {
      return customInstance<GetMe200>(
      {url: `/me`, method: 'GET'
    },
      );
    }
  
const postRefreshToken = (
    postRefreshTokenBody: PostRefreshTokenBody,
 ) => {
      return customInstance<PostRefreshToken200>(
      {url: `/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRefreshTokenBody
    },
      );
    }
  
const getExpenses = (
    params: GetExpensesParams,
 ) => {
      return customInstance<GetExpenses200>(
      {url: `/expenses`, method: 'GET',
        params
    },
      );
    }
  
const postExpenses = (
    postExpensesBody: PostExpensesBody,
 ) => {
      return customInstance<PostExpenses201>(
      {url: `/expenses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postExpensesBody
    },
      );
    }
  
const getExpensesSummary = (
    params: GetExpensesSummaryParams,
 ) => {
      return customInstance<GetExpensesSummary200>(
      {url: `/expenses/summary`, method: 'GET',
        params
    },
      );
    }
  
return {postRegisters,postSessions,getMe,postRefreshToken,getExpenses,postExpenses,getExpensesSummary}};
export type PostRegistersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['postRegisters']>>>
export type PostSessionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['postSessions']>>>
export type GetMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['getMe']>>>
export type PostRefreshTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['postRefreshToken']>>>
export type GetExpensesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['getExpenses']>>>
export type PostExpensesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['postExpenses']>>>
export type GetExpensesSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGoTrackApi>['getExpensesSummary']>>>
