/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetExpenses200ExpensesItem } from './getExpenses200ExpensesItem';

export type GetExpenses200 = {
  expenses: GetExpenses200ExpensesItem[];
};
