/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetExpenses200ExpensesItemCreatedAt } from './getExpenses200ExpensesItemCreatedAt';
import type { GetExpenses200ExpensesItemUpdatedAt } from './getExpenses200ExpensesItemUpdatedAt';

export type GetExpenses200ExpensesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  userId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string;
  service: string;
  title: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  value: number;
  createdAt: GetExpenses200ExpensesItemCreatedAt;
  updatedAt: GetExpenses200ExpensesItemUpdatedAt;
};
