/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetExpensesSummary200SummaryItem } from './getExpensesSummary200SummaryItem';

export type GetExpensesSummary200 = {
  summary: GetExpensesSummary200SummaryItem[];
};
