/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe200User } from './getMe200User';

export type GetMe200 = {
  user: GetMe200User;
};
