/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe200UserAvatarUrl } from './getMe200UserAvatarUrl';

export type GetMe200User = {
  id: string;
  name: string;
  email: string;
  avatarUrl: GetMe200UserAvatarUrl;
};
