/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */

export type PostExpensesBody = {
  /** @minLength 4 */
  title: string;
  /** @minLength 1 */
  service: string;
  /** @minimum 1 */
  value: number;
};
