/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Go-track-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * Sucesso
 */
export type PostRegisters201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  userId: string;
};
